import { useEffect, useState, useCallback } from "react";
import { RefreshCw, Sparkles, Zap, Bot } from "lucide-react";
import * as api from "../api.js";
import Pipeline from "../components/Pipeline.jsx";

const CATEGORY_LABEL = {
  energy: "Energy", fleet: "Fleet", renewable: "Renewable", process: "Process"
};

export default function AiInsights() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState(null);

  const load = useCallback(async (refresh = false) => {
    refresh ? setRefreshing(true) : setLoading(true);
    try {
      setData(await api.getAiInsights(undefined, refresh));
      setError(null);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { load(false); }, [load]);

  return (
    <>
      {error && <div className="error-banner">{error}</div>}

      <div className="card" style={{ marginBottom: 20 }}>
        <div className="kpi-label" style={{ marginBottom: 10 }}>Where this recommendation came from</div>
        <Pipeline activeIndex={4} />
      </div>

      <div className="section-title">
        <h2>Recommendations</h2>
        <button className="btn btn-secondary" onClick={() => load(true)} disabled={refreshing}>
          <RefreshCw size={13} className={refreshing ? "spin" : ""} />
          {refreshing ? "Refreshing…" : "Refresh"}
        </button>
      </div>

      {data && (
        <div className="source-note">
          {data.source === "groq" ? <Sparkles size={13} /> : <Bot size={13} />}
          {data.source === "groq"
            ? `Generated by ${data.model} (via Groq) from your live emissions data`
            : `Rule-based recommendations (${data.fallbackReason || "AI engine not configured"}) — still computed from your real data, not random`}
          {data.cached && " · cached (refresh for a new pass)"}
        </div>
      )}

      {loading && <div className="loading-block">Analyzing emissions data…</div>}

      {!loading && data && (
        <div className="grid grid-2">
          {data.recommendations.map((rec, i) => (
            <div key={i} className="rec-card">
              <div className="rec-card-head">
                <div className="rec-card-title">{rec.title}</div>
                <div className="rec-saving">
                  <Zap size={12} style={{ verticalAlign: -1 }} /> {rec.expectedSavingPercent}%
                </div>
              </div>
              <div className="rec-card-detail">{rec.detail}</div>
              <div className="rec-meta">
                <span className={`priority-${rec.priority}`} style={{ fontSize: 12, fontWeight: 600, textTransform: "capitalize" }}>
                  {rec.priority} priority
                </span>
                <span className="dot-sep">·</span>
                <span style={{ fontSize: 12, color: "var(--ink-soft)" }}>{CATEGORY_LABEL[rec.category] || rec.category}</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </>
  );
}
